name: Dev App Build

on:
  push:
    branches:
    - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
        clean: 'true'
        token: '${{ secrets.GIT_TOKEN }}'
        submodules: 'recursive'
        fetch-depth: '0'
        
    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
    - run: npm install

    - name: Building docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        context: .
        file: Dockerfile
        tags: |
          godspeedsystems/gs-node-service:dev
          adminmindgrep/gs_service:dev        
                    
    - name: Login to Godspeed DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.GODSPEED_DOCKERHUB_USERNAME }}
        password: ${{ secrets.GODSPEED_DOCKERHUB_PASSWORD }}

    - name: Pushing image into godspeed registry 
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          godspeedsystems/gs-node-service:dev

    - name: Login to mindgrep DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pushing image into adminmindgrep registry
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          adminmindgrep/gs_service:dev

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'godspeedsystems/gs-node-service:dev'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,CRITICAL,HIGH'          