name: Master App Build

on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
        clean: 'true'
        token: '${{ secrets.GIT_TOKEN }}'
        submodules: 'recursive'
        fetch-depth: '0'        

    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        
    - run: npm install
            
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Building docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        context: .
        file: Dockerfile
        tags: |
          godspeedsystems/gs_node_service:latest
          adminmindgrep/gs_service:latest        
                    
    - name: Login to Godspeed DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.GODSPEED_DOCKERHUB_USERNAME }}
        password: ${{ secrets.GODSPEED_DOCKERHUB_PASSWORD }}

    - name: Pushing image into godspeed registry 
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          godspeedsystems/gs_node_service:latest

    - name: Login to mindgrep DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pushing image into adminmindgrep registry 
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          adminmindgrep/gs_service:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'godspeedsystems/gs_node_service:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,CRITICAL,HIGH'   

    # - name: Setup Node.js v16
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 16.15.1

    # - name: Setup dependencies
    #   run: |
    #     npm install @semantic-release/git @semantic-release/exec --no-save

    # - name: Create Release
    #   env:
    #     GH_TOKEN: ${{ secrets.GIT_TOKEN }}
    #     NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    #     GIT_AUTHOR_NAME: "github release"
    #     GIT_AUTHOR_EMAIL: "admin@mindgrep.com"
    #     GIT_COMMITTER_NAME: "github release"
    #     GIT_COMMITTER_EMAIL: "admin@mindgrep.com"
    #   run: npx semantic-release        
