name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        clean: 'true'
        token: '${{ secrets.GIT_TOKEN }}'
        submodules: 'recursive'
        fetch-depth: '0'        

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
    - run: npm install        

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        tags: adminmindgrep/gs_service:${{ github.ref_name }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Building docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        context: .
        file: Dockerfile
        tags: |
          godspeedsystems/gs_node_service:${{ github.ref_name }}
          adminmindgrep/gs_service:${{ github.ref_name }}        
                    
    - name: Login to Godspeed DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.GODSPEED_DOCKERHUB_USERNAME }}
        password: ${{ secrets.GODSPEED_DOCKERHUB_PASSWORD }}

    - name: Pushing image into godspeed registry 
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          godspeedsystems/gs_node_service:${{ github.ref_name }}

    - name: Login to mindgrep DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name:  Pushing image into adminmindgrep registry
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          adminmindgrep/gs_service:${{ github.ref_name }}
